apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment-datacenter
spec:
  selector:
    matchLabels:
      app: httpd_app_datacenter
  replicas: 2
  template:
    metadata:
      labels:
        app: httpd_app_datacenter
    spec:
      containers:
      - name: httpd-container-datacenter
        image: udaisoni95/project2-image
        ports:
        - containerPort: 80
