apiVersion: v1
kind: Service
metadata:
  name: httpd-service-datacenter
  labels:
    app: httpd_app_datacenter
spec:
  type: NodePort
  ports:
    - nodePort: 30008
      port: 80
      targetPort: 80
  selector:
    app: httpd_app_datacenter
